paths:
  raw_car_data: data/raw/car_data.csv
  raw_consumer_data: data/raw/consumer_data.csv
  cleaned_car_data: data/cleaned/cleaned_car_data.csv
  cleaned_consumer_data: data/cleaned/cleaned_consumer_data.csv

database:
  user: postgres
  password: Fly140401.
  host: localhost
  port: 5432
  dbname: automotive_project
  car_table: car_data
  consumer_table: consumer_data